POST http://127.0.0.1:8000/
Content-Type: application/json


{
    "name": "Creed",
    "genre": "rock",
    "albums": [
        {
            "title": "Weathered", 
            "release_date": "2001-11-20"
        },
        {
            "title": "Full Circle", 
            "release_date": "2009-10-27"
        }
    ]
}




###
GET http://127.0.0.1:8000/bands/list/?genre=rock